version: "3.9"
services:
  web:
    container_name: 'atlanta-server'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3070:${PORT}"
  postgres:
    image: postgres:10.5
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
