apiVersion: v1
kind: Service
metadata:
  name: atlanta-server
spec:
  selector:
    app: atlanta-server
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3000
  type: NodePort
  externalIPs:
    - 192.168.0.108