apiVersion: v1
kind: Service
metadata:
  name: atlanta-server
spec:
  selector:
    app: atlanta-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  externalIPs:
    - 127.0.0.1